<?php
$ocInstances = array(
		"instance1"=>array(
				"name"=>"OCInstance1",
				"ocUrl"=>"http://myserver.com/OpenClinica/",
				"ocWSUrl"=>"http://myserver.com/OpenClinica-ws/",
				"ocUserName"=>"user1",
				"ocPassword"=>"pass1insha1",
				"ocDB"=>"",
				"ocDBHost"=>"",
				"ocDBUser"=>"",
				"ocDBPass"=>""
		),
		"instance2"=>array(
				"name"=>"OCInstance2",
				"ocUrl"=>"http://myserver.com/OpenClinica2/",
				"ocWSUrl"=>"http://myserver.com/OpenClinica2-ws/",
				"ocUserName"=>"user2",
				"ocPassword"=>"pass2insha1",
				"ocDB"=>"",
				"ocDBHost"=>"",
				"ocDBUser"=>"",
				"ocDBPass"=>""
		)
);
?>